function(evolution_enable_sanitizers target)
    if(MSVC)
        if(EVOLUTION_ENABLE_ADDRESS_SANITIZER)
            target_compile_options(${target} PRIVATE /fsanitize=address)
        endif()
        return()
    endif()

    set(enabled_sanitizers "")
    if(EVOLUTION_ENABLE_ADDRESS_SANITIZER)
        list(APPEND enabled_sanitizers address)
    endif()
    if(EVOLUTION_ENABLE_UNDEFINED_SANITIZER)
        list(APPEND enabled_sanitizers undefined)
    endif()

    if(enabled_sanitizers)
        list(JOIN enabled_sanitizers "," sanitizer_list)
        target_compile_options(${target} PRIVATE "-fsanitize=${sanitizer_list}" -fno-omit-frame-pointer)
        target_link_options(${target} PRIVATE "-fsanitize=${sanitizer_list}")
    endif()
endfunction()
